CREATE DATABASE escuela_bd;

USE escuela_bd;

CREATE TABLE estudiantes(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,	
    eamil VARCHAR(100) NOT NULL
);

